### ISSUE TITLE
I have a problem to install it

### ISSUE THREAD

**Issue by rilc0n** [glogiotatidis/tg-relay#2]
Where do I have to put down the .env file? What must be written in there.

When I run `python3 listchannels.py` I get the following message:

```
Traceback (most recent call last):
  File "listchannels.py", line 6, in <module>
    import config
  File "/home/arturweiss/tg-relay/config.py", line 3, in <module>
    API_ID = config('1129586')
  File "/home/arturweiss/.local/lib/python3.7/site-packages/decouple.py", line 199, in __call__
    return self.config(*args, **kwargs)
  File "/home/arturweiss/.local/lib/python3.7/site-packages/decouple.py", line 83, in __call__
    return self.get(*args, **kwargs)
  File "/home/arturweiss/.local/lib/python3.7/site-packages/decouple.py", line 68, in get
    raise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))
decouple.UndefinedValueError: 1129586 not found. Declare it as envvar or define a default value.
```

**Comment by glogiotatidis** [comment]
Instead on changing `config.py` as you did, you should add the config values in your `.env` like this

`
API_ID =1129586
...
`

**Comment by rilc0n** [comment]
Okay, thank you
